service:
  name: runk

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline-ssm
  - serverless-offline-sqs
  - serverless-offline

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
    excludedFiles: src/**/*.test.*
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    port: 3001
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: false
      migrate: true
      dbPath: ./db
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: ${self:custom.region}
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

package:
  individually: false

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  environment:
    DB_TABLE_USER: ${self:service.name}-${self:custom.stage}-user
    DB_TABLE_AUTHORIZER: ${self:service.name}-${self:custom.stage}-authorizer
    DB_TABLE_LEAGUE: ${self:service.name}-${self:custom.stage}-league
    DB_TABLE_MATCH: ${self:service.name}-${self:custom.stage}-match
    GOOGLE_CLIENT_ID: ${ssm:/runk/${self:custom.stage}/googleClientId}
    GOOGLE_CLIENT_SECRET: ${ssm:/runk/${self:custom.stage}/googleClientSecret~true}
    JWT_SECRET: ${ssm:/runk/${self:custom.stage}/jwtSecret~true}
    QUEUE_RECALCULATE: ${self:service.name}-${self:custom.stage}-recalculate
    REGION: ${self:custom.region}
    STAGE: ${self:custom.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ UserTable, Arn ]
        - "Fn::GetAtt": [ AuthorizerTable, Arn ]
        - "Fn::GetAtt": [ MatchTable, Arn ]
        - "Fn::GetAtt": [ LeagueTable, Arn ]
        - "Fn::Join":
          - '/'
          - - "Fn::GetAtt": [ MatchTable, Arn ]
            - "index"
            - "leagueId-index"

functions:
  - ${file(resources/functions-auth.yml)}
  - ${file(resources/functions-league.yml)}
  - ${file(resources/functions-discover.yml)}
  - ${file(resources/functions-match.yml)}
  - ${file(resources/functions-user.yml)}

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/queue.yml)}
