service:
  name: runk

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
    excludedFiles: src/**/*.test.*

package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: eu-central-1
  environment:

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
