Resources:
  UserTable:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:provider.environment.DB_TABLE_USER}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
  AuthorizerTable:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:provider.environment.DB_TABLE_AUTHORIZER}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
        -
          AttributeName: type
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
        -
          AttributeName: type
          KeyType: RANGE
  LeagueTable:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:provider.environment.DB_TABLE_LEAGUE}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
  MatchTable:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:provider.environment.DB_TABLE_MATCH}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
        - 
          AttributeName: leagueId
          AttributeType: S
        -
          AttributeName: date
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      GlobalSecondaryIndexes:
        -
          IndexName: leagueId-index
          KeySchema:
            -
              AttributeName: leagueId
              KeyType: HASH
            - 
              AttributeName: date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
